# Generated by Django 5.2.11 on 2026-07-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('nid_number', models.CharField(help_text='National ID / Passport number', max_length=30, unique=True)),
                ('nid_image', models.ImageField(blank=True, null=True, upload_to='seller_nid/')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='seller_pics/')),
                ('company_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('business_type', models.CharField(choices=[('individual', 'Individual / Sole Proprietor'), ('company', 'Registered Company'), ('partnership', 'Partnership')], default='individual', max_length=20)),
                ('trade_license', models.CharField(blank=True, help_text='Trade license number', max_length=100, null=True)),
                ('trade_license_image', models.ImageField(blank=True, null=True, upload_to='seller_trade/')),
                ('tin_number', models.CharField(blank=True, help_text='TIN / VAT number', max_length=50, null=True)),
                ('business_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='seller_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='seller_banners/')),
                ('category', models.CharField(blank=True, help_text='Main product category', max_length=100, null=True)),
                ('division', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('upazila', models.CharField(blank=True, max_length=100, null=True)),
                ('full_address', models.TextField()),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('bkash_number', models.CharField(blank=True, max_length=20, null=True)),
                ('nagad_number', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('banned', 'Banned')], db_index=True, default='pending', max_length=15)),
                ('rejection_note', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('total_products', models.PositiveIntegerField(default=0)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seller',
                'verbose_name_plural': 'Sellers',
                'db_table': 'sellers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sellers.seller')),
            ],
            options={
                'db_table': 'seller_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
