# Generated by Django 5.2.11 on 2026-04-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
        ('product', '0003_product_search_vector_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug'], name='product_pro_slug_33a021_idx'),
        ),
    ]
