"""
Django settings for somagom project.

Generated by 'django-admin startproject' using Django 3.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
import dj_database_url

load_dotenv()

LOG_BASE_DIR = Path(__file__).resolve().parent.parent / "logs"
LOG_BASE_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "class": "logging.FileHandler",
            "level": "ERROR",
            "filename": str(LOG_BASE_DIR / "django_error.log"),
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": True,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# settings.py
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'somagoam.com',
    'www.somagoam.com',
    'your-ngrok-url.ngrok-free.dev',
    '.ondigitalocean.app',
]


# Application definition

INSTALLED_APPS = [
    'admin_tools_stats',#new
    'django_nvd3',#new
    'jazzmin',#new
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #extra
    'django.contrib.postgres',
    'django.contrib.sites',
    #3rd party
    'rest_framework',
    'rest_framework.authtoken',
    'django_filters',
    'corsheaders',
    'rest_framework_simplejwt.token_blacklist',
        #Dj rest auth
    'dj_rest_auth',
    'dj_rest_auth.registration',
        #Allauth and registration
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    "allauth.socialaccount.providers.google",#new
    "allauth.socialaccount.providers.facebook",#new

    'storages',#new
    
    #local
    'users',
    'product.apps.ProductConfig',
    'category',
    'order',
    'payment',
    'cart',
    'reviews',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',#new for static file serving in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    #corsheaders
    'corsheaders.middleware.CorsMiddleware',  #new

    'django.middleware.common.CommonMiddleware',
    'django.middleware.gzip.GZipMiddleware',#new for response compression
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #allauth middleware
    'allauth.account.middleware.AccountMiddleware',#new
]
    

ROOT_URLCONF = 'somagom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'somagom.wsgi.application'


#acces forntend
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    'https://somagoam.com',
    "https://www.somagoam.com",
    "https://somagoam-database-dlilb.ondigitalocean.app",

]

CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 
                        'http://127.0.0.1:8000', 
                        'http://localhost:3000', 
                        'http://localhost:5173',
                        'https://somagoam.com',
                        'https://www.somagoam.com',
                        'https://somagoam-database-dlilb.ondigitalocean.app'

]


# redirects user to your React frontend after email verification
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = f'{FRONTEND_URL}/login'
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = f'{FRONTEND_URL}/login'
LOGIN_REDIRECT_URL = f'{FRONTEND_URL}/social-callback'
LOGIN_URL = f'{FRONTEND_URL}/login'



#Authentication Backends
AUTHENTICATION_BACKENDS = [

    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

#social account providers settings
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": ["profile", "email"],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "OAUTH_PKCE_ENABLED": True,
        "FETCH_USERINFO": True,
    },

    "facebook": {
        "METHOD": "oauth2",
        "SCOPE": ["email", "public_profile"],
        "FIELDS": [
            "id",
            "email",
            "name",
            "first_name",
            "last_name",
            "picture",
        ],
        "VERIFIED_EMAIL": False,
        "VERSION": "v13.0",
    }
}

SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_LOGIN_ON_GET = True


#DRF
REST_FRAMEWORK={
    'DEFAULT_AUTHENTICATION_CLASSES':(
    
        'users.authentication.CsrfExemptSessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    ),
    'DEFAULT_PERMISSION_CLASSES':(
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':10,

    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',    #rate limit
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '70/minute',  
        'user': '100/minute',
        'payment_init': '5/minute',
        'dj_rest_auth': '20/minute',#dj_rest_auth
        
    }
}
#allauth 
ACCOUNT_RATE_LIMITS = {
    'login_failed': '5/5m',         
    'login': '10/m',         
    'signup': '3/h',                
    'password_reset': '2/1h',   
}

#JWT

SIMPLE_JWT={
    'ACCESS_TOKEN_LIFETIME':timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME':timedelta(days=7),
    'AUTH_HEADER_TYPES':('Bearer',),
    'BLACKLIST_AFTER_ROTATION': True,
}

#dj-rest-auth
REST_AUTH={

    'USE_JWT':True,
    'JWT_AUTH_HTTPONLY': False,
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases




DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB'),
        'USER': os.getenv('POSTGRES_USER'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'db'),
        'PORT': "5432",
    }
}






db_from_env = dj_database_url.config(conn_max_age=600,ssl_require=True)
if db_from_env:
    DATABASES['default'].update(db_from_env)
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS =[]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL='users.User'

# Celery Settings
REDIS_URL = os.getenv('REDIS_URL', 'redis://redis:6379/0')


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 1000,
                "retry_on_timeout": True,
            }
        },
        
    }
}

CACHE_TTL = 60 * 15


#celery settings

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_TASK_ACKS_LATE = True        # only mark task done after success
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # re-queue if worker crashes





#allauth,dj-rest-auth

# ACCOUNT_AUTHENTICATION_METHOD='email'
# ACCOUNT_EMAIL_REQUIRED=True

ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# ACCOUNT_USERNAME_REQUIRED=False
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'username'

ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
#dj-rest-auth registration serializer


#media
MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media')


#sslcommerz
SSLCOMMERZ_STORE_ID=os.getenv('SSLCOMMERZ_STORE_ID')
SSLCOMMERZ_STORE_PASS=os.getenv('SSLCOMMERZ_STORE_PASS')
SSLCOMMERZ_IS_SANDBOX = True


#celery settings
CELERY_BEAT_SCHEDULE = {
    "cancel-expired-orders": {
        "task": "payment.tasks.cancel_expired_orders",
        "schedule": 300.0,
    },
}
CELERY_EMAIL_TASK_CONFIG = {
    'max_retries': 3,
    'default_retry_delay': 30,
    'ignore_result': True,
}




# Email Settings (Gmail Example)
#  prints email to terminal instead of sending — perfect for developm
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
CELERY_EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = f'Somagom <{os.getenv("EMAIL_HOST_USER")}>'
EMAIL_TIMEOUT = 11





#session settings

SESSION_COOKIE_HTTPONLY = True #prevent JS access to session cookie and xss attack
SESSION_COOKIE_SAMESITE = "Lax"


#for session using redis cache.

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


#CSRF Settings
CSRF_COOKIE_HTTPONLY = False   # must be readable by JS
CSRF_COOKIE_SAMESITE = "Lax"
CORS_ALLOW_CREDENTIALS = True # allow cookies/session/JWT
  
#SECURE Cookies and https
if not DEBUG:
    SECURE_SSL_REDIRECT = False # redirect all HTTP to HTTPS 
    SECURE_HSTS_SECONDS = 31536000  # protect ssl stripping attack  
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SESSION_COOKIE_SECURE = False # only over HTTPS
    CSRF_COOKIE_SECURE = False     # only over HTTPS

else:
    SECURE_SSL_REDIRECT = False

SITE_ID = 1



# # AWS s3 settings for media file storage
# AWS_ACCESS_KEY_ID = 'your-access-key-id'
# AWS_SECRET_ACCESS_KEY = 'your-secret-access-key'
# AWS_STORAGE_BUCKET_NAME = 'your-bucket-name'
# AWS_S3_REGION_NAME = 'ap-south-1'  # s3 bucket region
# AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# # media
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None
# AWS_S3_VERIFY = True

# # set s3 as default file storage
# DEFAULT_FILE_STORAGE = 'payment.storage_backends.MediaStorage'

# # media file URL
# MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/media/'


if DEBUG:
    
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
else:
    
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = f'https://sgp1.digitaloceanspaces.com' 
    AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.sgp1.digitaloceanspaces.com'
    
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = 'public-read'
    
    
    DEFAULT_FILE_STORAGE = 'payment.storage_backends.MediaStorage'
    MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/'



