# Generated by Django 5.2.11 on 2026-03-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_tran_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='card_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tran_id',
            field=models.CharField(default=0, help_text='Merchant Transaction ID', max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='val_id',
            field=models.CharField(blank=True, help_text='SSLCommerz Validation ID', max_length=150, null=True),
        ),
    ]
