# Generated by Django 5.2.11 on 2026-03-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_bank_tran_id_order_card_type_order_tran_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tran_id',
            field=models.CharField(help_text='Merchant Transaction ID', max_length=150, unique=True),
        ),
    ]
