# Generated by Django 5.2.11 on 2026-03-31 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_tran_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tran_id',
            field=models.CharField(blank=True, help_text='Merchant Transaction ID', max_length=150, null=True, unique=True),
        ),
    ]
