# Generated by Django 5.2.11 on 2026-04-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tran_id',
            field=models.CharField(blank=True, db_index=True, help_text='Merchant Transaction ID', max_length=150, null=True, unique=True),
        ),
    ]
