# Generated by Django 5.2.11 on 2026-03-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(help_text='Merchant Transaction ID', max_length=150, unique=True)),
                ('val_id', models.CharField(blank=True, help_text='SSLCommerz Validation ID', max_length=150, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_tran_id', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='order.order')),
            ],
        ),
    ]
