# Generated by Django 5.2.11 on 2026-06-10 23:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_payment_bank_tran_id_remove_payment_card_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BkashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('payment_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('trx_id', models.CharField(blank=True, max_length=128, null=True)),
                ('merchant_invoice_no', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=20)),
                ('create_response', models.JSONField(blank=True, null=True)),
                ('execute_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bKash Payment',
                'verbose_name_plural': 'bKash Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
