# Generated by Django 5.2.11 on 2026-04-10 23:44

import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=order.models.get_expiry, null=True),
        ),
    ]
