# Generated by Django 5.2.11 on 2026-04-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_tran_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='sender_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
