# Generated by Django 5.2.11 on 2026-04-12 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_is_verified_order_sender_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='method',
            field=models.CharField(blank=True, choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('cod', 'Cod')], max_length=20, null=True),
        ),
    ]
