# Generated by Django 5.2.11 on 2026-04-12 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_order_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='order',
            name='method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sender_number',
        ),
    ]
